# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 345378da4809a1e32f28698b34e11f2cea69c775151393d1d4e4d6506b658c11b91e4e7f9266cc499ee5b429640b7a150e08fe2363b0230a081888e4ce49e1ca

test:
  secret_key_base: 2481bb5e93553dc99e4d1edb6a4a8fbe459f2c1383df39b9551c998b540ababd1ec552501dab291256a393daae83f6f43b40b0dd2768b0e4125fccc9d6ba9bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
